name: pytest
on: pull_request

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Calculate pyproject.toml SHA
        id: pyproject_toml_dockerfile_sha
        uses: ./.github/actions/sha
        with:
          path: ${{github.event.repository.name}}/pyproject.toml ${{github.event.repository.name}}/Dockerfile
      - id: lowercase_tags
        uses: ./.github/actions/change_string_case
        with:
          string: quay.io/${{ vars.QUAY_ORG }}/${{github.event.repository.name}}:${{steps.pyproject_toml_dockerfile_sha.outputs.sha}}
      - name: tag exists
        id: tag_exists
        uses: ./.github/actions/tag_exists
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}
          tag: ${{ steps.lowercase_tags.outputs.lowercase }}
          sha_path: ${{github.event.repository.name}}/pyproject.toml ${{github.event.repository.name}}/Dockerfile
      - name: Login to quay.io
        uses: docker/login-action@v3
        if: ${{steps.tag_exists.outputs.tag_exists == 'false'}}
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: ${{steps.tag_exists.outputs.tag_exists == 'false'}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
        if: ${{steps.tag_exists.outputs.tag_exists == 'false'}}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{github.event.repository.name}}"
          push: true
          tags: ${{ steps.lowercase_tags.outputs.lowercase }}
        if: ${{steps.tag_exists.outputs.tag_exists == 'false'}}

  pytest:
    name: pytest
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - uses: actions/checkout@v5
      - name: Calculate pyproject.toml SHA
        id: pyproject_toml_dockerfile_sha
        uses: ./.github/actions/sha
        with:
          path: ${{github.event.repository.name}}/pyproject.toml ${{github.event.repository.name}}/Dockerfile
      - id: lowercase_tags
        uses: ./.github/actions/change_string_case
        with:
          string: quay.io/${{ vars.QUAY_ORG }}/${{github.event.repository.name}}:${{steps.pyproject_toml_dockerfile_sha.outputs.sha}}
      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: pytest
        run: |
          echo pulling
          docker pull ${{steps.lowercase_tags.outputs.lowercase}}
          echo running
          docker run -dit --name pytestcontainer --mount type=bind,src=.,dst=/CI ${{steps.lowercase_tags.outputs.lowercase}}
          echo executing
          docker exec pytestcontainer uv run pytest /CI/${{github.event.repository.name}}

  ruff-lint:
    name: ruff python linting
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - uses: actions/checkout@v5
      - name: Calculate pyproject.toml SHA
        id: pyproject_toml_dockerfile_sha
        uses: ./.github/actions/sha
        with:
          path: ${{github.event.repository.name}}/pyproject.toml ${{github.event.repository.name}}/Dockerfile
      - id: lowercase_tags
        uses: ./.github/actions/change_string_case
        with:
          string: quay.io/${{ vars.QUAY_ORG }}/${{github.event.repository.name}}:${{steps.pyproject_toml_dockerfile_sha.outputs.sha}}
      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: ruff-lint
        run: |
          echo pulling
          docker pull ${{steps.lowercase_tags.outputs.lowercase}}
          echo running
          docker run -dit --name pytestcontainer --mount type=bind,src=.,dst=/CI ${{steps.lowercase_tags.outputs.lowercase}}
          echo executing
          docker exec pytestcontainer ruff check /CI/${{github.event.repository.name}}

  mypy-typecheck:
    name: mypy python typechecking
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - uses: actions/checkout@v5
      - name: Calculate pyproject.toml SHA
        id: pyproject_toml_dockerfile_sha
        uses: ./.github/actions/sha
        with:
          path: ${{github.event.repository.name}}/pyproject.toml ${{github.event.repository.name}}/Dockerfile
      - id: lowercase_tags
        uses: ./.github/actions/change_string_case
        with:
          string: quay.io/${{ vars.QUAY_ORG }}/${{github.event.repository.name}}:${{steps.pyproject_toml_dockerfile_sha.outputs.sha}}
      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: mypy-typecheck
        run: |
          echo pulling
          docker pull ${{steps.lowercase_tags.outputs.lowercase}}
          echo running
          docker run -dit --name pytestcontainer --mount type=bind,src=.,dst=/CI ${{steps.lowercase_tags.outputs.lowercase}}
          echo executing
          docker exec pytestcontainer mypy /CI/${{github.event.repository.name}}
